# Generated by Django 4.0.6 on 2022-07-09 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ativacao',
            options={'verbose_name': 'Ativação', 'verbose_name_plural': 'Ativações'},
        ),
        migrations.AlterModelTable(
            name='ativacao',
            table='Ativacao',
        ),
    ]
